language: c
compiler:
  - gcc
install:
  # remove gcc to take the 4.8
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get remove gcc g++
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
script:
# compile the engine
  - cd build/cmake && cmake . && make
# todo: run the tests 
